name: Telegram Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'  # 15 မိနစ် အကြိမ်နှုန်း

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: python bot.py
